version: '3.2'
services:
  kafka-0:
    image: bitnami/kafka:3.3.1
    environment:
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: r7dMBY60T16TrNCGeXniLw
      KAFKA_CFG_PROCESS_ROLES: controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: CONTROLLER://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: " "
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_BROKER_ID: 0
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"

  kafka-1:
    image: bitnami/kafka:3.3.1
    environment:
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: r7dMBY60T16TrNCGeXniLw
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: BROKER://:9092, LOCALHOST://:9081
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT, CONTROLLER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka-1:9092, LOCALHOST://localhost:9081
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - 9081:9081
    depends_on:
      - kafka-0

  kafka-2:
    image: bitnami/kafka:3.3.1
    environment:
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: r7dMBY60T16TrNCGeXniLw
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: BROKER://:9092, LOCALHOST://:9082
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT, CONTROLLER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka-2:9092, LOCALHOST://localhost:9082
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - 9092:9082
      - 9082:9082
    networks:
      default:
        aliases:
          - kafka
    depends_on:
      - kafka-0

  kafka-3:
    image: bitnami/kafka:3.3.1
    environment:
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_KRAFT_CLUSTER_ID: r7dMBY60T16TrNCGeXniLw
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: BROKER://:9092, LOCALHOST://:9083
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT, CONTROLLER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka-3:9092, LOCALHOST://localhost:9083
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - 9083:9083
    depends_on:
      - kafka-0


  setup:
    image: juplo/toolbox
    command: >
      bash -c "
        kafka-topics --bootstrap-server kafka:9092 --delete --if-exists --topic test
        kafka-topics --bootstrap-server kafka:9092 --create --topic test --partitions 2 --replication-factor 3 --config min.insync.replicas=2
        kafka-topics --bootstrap-server kafka:9092 --describe --topic test
      "
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - cli

  akhq:
    image: tchiotludo/akhq:0.23.0
    ports:
      - 8000:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  cli:
    image: juplo/toolbox
    command: sleep infinity
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
