juplo:
  bootstrap-server: :9092
  client-id: DEV
  consumer:
    group-id: nodlt
    topic: test
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
    java:
      enabled: true
info:
  kafka:
    bootstrap-server: ${juplo.bootstrap-server}
    client-id: ${juplo.client-id}
    consumer:
      group-id: ${juplo.consumer.group-id}
      topic: ${juplo.consumer.topic}
logging:
  level:
    root: INFO
    de.juplo: DEBUG
    org.springframework.kafka: INFO
server:
  port: 8881
