services:
  controller:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@controller:9093
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - controller-data:/var/lib/kafka/data
    stop_grace_period: 120s

  kafka-1:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://:9092, LOCALHOST://:9081
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-1:9092, LOCALHOST://localhost:9081
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT, BROKER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@controller:9093
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 1000
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-1-data:/var/lib/kafka/data
    ports:
      - 9081:9081
    stop_grace_period: 120s
    depends_on:
      - controller

  kafka-2:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://:9092, LOCALHOST://:9082
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-2:9092, LOCALHOST://localhost:9082
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT, BROKER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@controller:9093
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 1000
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-2-data:/var/lib/kafka/data
    ports:
      - 9092:9082
      - 9082:9082
    networks:
      default:
        aliases:
          - kafka
    stop_grace_period: 120s
    depends_on:
      - controller

  kafka-3:
    image: apache/kafka:4.1.1
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: BROKER://:9092, LOCALHOST://:9083
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-3:9092, LOCALHOST://localhost:9083
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT, BROKER:PLAINTEXT, LOCALHOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@controller:9093
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 1000
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-3-data:/var/lib/kafka/data
    ports:
      - 9083:9083
    stop_grace_period: 120s
    depends_on:
      - controller

  cli:
    image: juplo/toolbox
    command: sleep infinity
    stop_grace_period: 0s
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

  setup:
    image: juplo/toolbox
    command:
      - bash
      - -c
      - |
        cub kafka-ready -b kafka-1:9092,kafka-2:9092,kafka-3:9092 3 60 > /dev/null 2>&1 || exit 1
        if [ -e INITIALIZED ]
        then
          echo -n Bereits konfiguriert: 
          cat INITIALIZED
          kafka-topics --bootstrap-server kafka:9092 --describe --topic test
        else
          kafka-topics --bootstrap-server kafka:9092 \
                       --delete \
                       --if-exists \
                       --topic test
          kafka-topics --bootstrap-server kafka:9092 \
                       --create \
                       --topic test \
                       --partitions 2 \
                       --replication-factor 3 \
                       --config min.insync.replicas=2 \
          && echo Das Topic \'test\' wurde erfolgreich angelegt: \
          && kafka-topics --bootstrap-server kafka:9092 --describe --topic test \
          && date > INITIALIZED
        fi
    stop_grace_period: 0s
    depends_on:
      - cli

  akhq:
    image: tchiotludo/akhq:0.23.0
    ports:
      - 8888:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                - name: "connect"
                  url: "http://connect:8083"
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3

volumes:
  controller-data:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:
